global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'python-app'
    static_configs:
      - targets: ['172.29.170.197:5000']
    metrics_path: /metrics